#!/usr/bin/env python3
"""tools/embed.py — bake compiled .mbc games into the kernel.

Usage: embed.py output.h game1.mbc game2.mbc ...
Game names come from the file stem.
"""
import sys
from pathlib import Path


def main():
    out, paths = sys.argv[1], sys.argv[2:]
    lines = [
        "/* generated by tools/embed.py — do not edit */",
        "#ifndef MEOW_GAMES_H",
        "#define MEOW_GAMES_H",
        "",
    ]
    names = []
    for p in map(Path, paths):
        data = p.read_bytes()
        name = p.stem
        names.append(name)
        body = ",".join(str(b) for b in data)
        lines.append(f"static const unsigned char game_{name}[] = {{{body}}};")
    lines += [
        "",
        "struct meow_game { const char *name; const unsigned char *data; int len; };",
        "static const struct meow_game meow_games[] = {",
    ]
    for name in names:
        lines.append(
            f'    {{ "{name}", game_{name}, (int)sizeof game_{name} }},'
        )
    lines += [
        "};",
        f"#define MEOW_NGAMES {len(names)}",
        "",
        "#endif",
        "",
    ]
    Path(out).write_text("\n".join(lines))


if __name__ == "__main__":
    main()
